server:
  port: 8081


oauth2:
  clientId: testClientId
  clientSecret: testSecret
  grantType: authorization_code
  callback: http://localhost:8081/oauth2/callback
  token: http://localhost:8081/oauth/token


security:
  oauth2:
    jwt:
      signkey: 123@#$

spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    hikari:
      trade:
        jdbc-url: jdbc:oracle:thin:@(DESCRIPTION=(LOAD_BALANCE=off)(FAILOVER=on)(ADDRESS=(PROTOCOL=TCP)(HOST=120.143.250.142)(PORT=12533))(ADDRESS=(PROTOCOL=TCP)(HOST=120.143.250.144)(PORT=12533))(CONNECT_DATA=(SERVICE_NAME=BOA)))
        username: trade
        password: trade_dev
        driver-class-name: oracle.jdbc.OracleDriver

      sso:
        jdbc-url: jdbc:oracle:thin:@(DESCRIPTION=(LOAD_BALANCE=off)(FAILOVER=on)(ADDRESS=(PROTOCOL=TCP)(HOST=120.143.250.142)(PORT=12533))(ADDRESS=(PROTOCOL=TCP)(HOST=120.143.250.144)(PORT=12533))(CONNECT_DATA=(SERVICE_NAME=BOA)))
        username: sso
        password: sso_dev
        driver-class-name: oracle.jdbc.OracleDriver



    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: none
      # show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    org.hibernate.SQL: debug

    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.hbm2ddl.auto: none
    showSql: true