spring:
  datasource:
    hikari:
      trade:
        jdbc-url: jdbc:oracle:thin:@(DESCRIPTION=(LOAD_BALANCE=off)(FAILOVER=on)(ADDRESS=(PROTOCOL=TCP)(HOST=120.143.250.142)(PORT=12533))(ADDRESS=(PROTOCOL=TCP)(HOST=120.143.250.144)(PORT=12533))(CONNECT_DATA=(SERVICE_NAME=BOA)))
        username: trade
        password: trade_dev
        driver-class-name: oracle.jdbc.OracleDriver

      sso:
        jdbc-url: jdbc:oracle:thin:@(DESCRIPTION=(LOAD_BALANCE=off)(FAILOVER=on)(ADDRESS=(PROTOCOL=TCP)(HOST=120.143.250.142)(PORT=12533))(ADDRESS=(PROTOCOL=TCP)(HOST=120.143.250.144)(PORT=12533))(CONNECT_DATA=(SERVICE_NAME=BOA)))
        username: sso
        password: sso_dev
        driver-class-name: oracle.jdbc.OracleDriver



  jpa:
    hibernate:
      ddl-auto: none
      # show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    org.hibernate.SQL: debug
