server:
  port: 8080
spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.hbm2ddl.auto: create
    showSql: true

oauth2:
  clientId: testClientId1
  clientSecret: testSecret1
  grantType: authorization_code
  callback: http://localhost:8080/oauth2/callback
  token: http://localhost:8081/oauth/token

security:
  oauth2:
    jwt:
      signkey: 123@#$
    client:
      client-id: testClientId1
      client-secret: testSecret1
    resource:
      token-info-uri: http://localhost:8081/oauth/check_token